// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `transform_file`

Future<Uint8List> deriveKey({required String password}) =>
    RustLib.instance.api.crateApiCryptoDeriveKey(password: password);

Future<String> encryptMessage(
        {required String plaintext, required List<int> key}) =>
    RustLib.instance.api
        .crateApiCryptoEncryptMessage(plaintext: plaintext, key: key);

Future<String> decryptMessage({required String text, required List<int> key}) =>
    RustLib.instance.api.crateApiCryptoDecryptMessage(text: text, key: key);

Future<bool> looksEncrypted({required String text}) =>
    RustLib.instance.api.crateApiCryptoLooksEncrypted(text: text);

Future<void> encryptImageFile(
        {required String sourcePath,
        required String destPath,
        required List<int> key}) =>
    RustLib.instance.api.crateApiCryptoEncryptImageFile(
        sourcePath: sourcePath, destPath: destPath, key: key);

Future<void> decryptImageFile(
        {required String sourcePath,
        required String destPath,
        required List<int> key}) =>
    RustLib.instance.api.crateApiCryptoDecryptImageFile(
        sourcePath: sourcePath, destPath: destPath, key: key);

Future<bool> looksEncryptedImageFile({required String path}) =>
    RustLib.instance.api.crateApiCryptoLooksEncryptedImageFile(path: path);
